module.exports = {

  //solidoSidebar: [{type: 'autogenerated', dirName: '.'}],
  solidoSidebar: [
    {
      type: 'doc',
      id: 'overview',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Staking',
      items:[{type: 'autogenerated', dirName: 'staking',},],
    },
    {
      type: 'doc',
      id: 'the-solido-utility',
      label: 'The Solido utility',
    },
    {
      type: 'category',
      label: 'Governance',
      items:[{type: 'autogenerated', dirName: 'governance',},],
    },
    {
      type: 'doc',
      id: 'maintenance',
      label: 'Maintenance',
    },
    {
      type: 'category',
      label: 'Development',
      items:[{type: 'autogenerated', dirName: 'development',},],
    },
    {
      type: 'category',
      label: 'Internals',
      items:[{type: 'autogenerated', dirName: 'internals',},],
    },
    {
      type: 'doc',
      id: 'deployments',
      label: 'Deployments',
    },
  ],
};
