module.exports = {

  //solidoSidebar: [{type: 'autogenerated', dirName: '.'}],
  solidoSidebar: [
    {
      type: 'doc',
      id: 'overview',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Staking',
      items:[{type: 'autogenerated', dirName: 'Staking',},],
    },
    {
      type: 'category',
      label: 'Governance',
      items:[{type: 'autogenerated', dirName: 'Governance',},],
    },
    {
      type: 'category',
      label: 'Validation',
      items:[{type: 'autogenerated', dirName: 'Validation',},],
    },
    {
      type: 'category',
      label: 'Maintenance',
      items:[{type: 'autogenerated', dirName: 'Maintenance',},],
    },
    {
      type: 'category',
      label: 'Development',
      items:[{type: 'autogenerated', dirName: 'Development',},],
    },
  ],
};
